// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID    string `gorm:"type:uuid;default:gen_random_uuid();primaryKey"`
	Name  string
	Email string
	Posts []Post `gorm:"foreignKey:UserID"`
}

type Post struct {
	ID      string `gorm:"type:uuid;default:gen_random_uuid();primaryKey"`
	Title   string
	Content string
	UserID  string `gorm:"type:uuid"` // foreign key
	User    User   `gorm:"constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`
}
